# Generated by Django 3.0.7 on 2020-06-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pictures')),
                ('dis', models.TextField()),
                ('cont', models.FileField(upload_to='')),
            ],
        ),
    ]
